image: maven:latest

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile
    
package:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS package
    - mv target/CLIGui* .
  artifacts:
    name: build
    paths:
    - ./CLIGui*.jar